apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: prometheus
spec:
  interval: 5m
  chart:
    spec:
      version: 34.1.0
      chart: kube-prometheus-stack
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
      interval: 1m
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    alertmanager:
      enabled: false
    grafana:
      sidecar:
        dashboards:
          searchNamespace: ALL
    prometheus:
      prometheusSpec:
        podMonitorSelector:
          matchLabels:
            app.kubernetes.io/part-of: flux

---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: flux2-system
  namespace: flux2-system
  labels:
    app.kubernetes.io/part-of: flux
spec:
  namespaceSelector:
    matchNames:
      - flux2-system
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - helm-controller
          - source-controller
          - kustomize-controller
          - notification-controller
          - image-automation-controller
          - image-reflector-controller
  podMetricsEndpoints:
    - port: http-prom